### ISSUE TITLE
Cards should redirect to the event if possible

### ISSUE THREAD

**Issue by BRO3886** [GDGVIT/gidget#14]
* eg when a user creates the issue it should go to the issue instead of repo page
* Wherever it's not possible fallback to repo page

**Comment by rishavnaskar** [comment]
> * eg when a user creates the issue it should go to the issue instead of repo page
> * Wherever it's not possible fallback to repo page

Yeah, I had this in mind. I will start working on this.

**Comment by rishavnaskar** [comment]
> * eg when a user creates the issue it should go to the issue instead of repo page
> * Wherever it's not possible fallback to repo page

This is implemented and the code has been pushed.
