### ISSUE TITLE
Improve splash screen

### ISSUE THREAD

**Issue by BRO3886** [GDGVIT/gidget#25]
Splash screen logo looks smushed. Needs a fix.

https://user-images.githubusercontent.com/39856034/124249390-73f93080-db41-11eb-89cb-5fab8859af9b.mp4

**Comment by rishavnaskar** [comment]
Yes I will be updating this with a proper design after getting it from Pranjal.

**Comment by BRO3886** [comment]
Tag her on discord and keep in the loop

**Comment by rishavnaskar** [comment]
This is done @BRO3886
