### ISSUE TITLE
Authentication through Github app

### ISSUE THREAD

**Issue by saikun0293** [GDGVIT/gidget#30]
The app doesn't accept authentication through github app for me. It shows the same "Open with" section on selecting the github app authentication option. 

It works fine if I authenticate to github through google chrome though

**Comment by BRO3886** [comment]
Yes that's because github app then redirects to chrome and it works fine after that

**Comment by saikun0293** [comment]
for me it doesn't redirect to chrome. It just shows "Open with" again
