### ISSUE TITLE
Unable to find specific repos or orgs 

### ISSUE THREAD

**Issue by Nirmitjatana** [GDGVIT/gidget#32]
**This issue is extension of #23** 

**Describe the bug**
While using the search feature, sometimes I am not able to reach to desired repos or organizations.

**To Reproduce**
1. Click on search button.
2. Search for repos.

**Possible solution**
For repo, we can ask the user to give the input in the form of ```:organization/repo```, to get specific repos.

#### Is this is a critical secuirty vulnerability?
- [ ] Yes: Please read code-of-conduct once
- [x] No

**screenshots**
![image](https://user-images.githubusercontent.com/52108077/124431853-903ddd00-dd8e-11eb-9c30-3cb5e5ed3cac.png)
![image](https://user-images.githubusercontent.com/52108077/124431873-9633be00-dd8e-11eb-8876-74ff30b0015e.png)
![image](https://user-images.githubusercontent.com/52108077/124431883-99c74500-dd8e-11eb-95bf-1b3fdea35e8d.png)
![image](https://user-images.githubusercontent.com/52108077/124431927-a481da00-dd8e-11eb-85ca-01c4e84d2fb5.png)
![image](https://user-images.githubusercontent.com/52108077/124431934-a8156100-dd8e-11eb-8ca4-a09a7a74eb69.png)

**Comment by BRO3886** [comment]
wot

**Comment by BRO3886** [comment]
Org is `GDGVIT`

**Comment by Nirmitjatana** [comment]
@BRO3886 specific repo thing should be there if, in which you can search for repos in an org

**Comment by Nirmitjatana** [comment]
My bad it is already there!

**Comment by rishavnaskar** [comment]
## Okay. So I will be attaching a couple of images here @Nirmitjatana ##

### 1. WikiWeb isnt there in GDGVIT repositories ###

![image](https://user-images.githubusercontent.com/59786899/124433203-1d356600-dd90-11eb-8edd-0fbed7a0e009.png)

### 2. For Cadence ###

![image](https://user-images.githubusercontent.com/59786899/124433494-70a7b400-dd90-11eb-8a63-bd004151c297.png)

### 3. DSC VIT still has its name as GDGVIT in GitHub... ###

![image](https://user-images.githubusercontent.com/59786899/124433880-dac05900-dd90-11eb-875a-8cb6098db9d6.png)
