### ISSUE TITLE
Adding your profile to widget

### ISSUE THREAD

**Issue by Nirmitjatana** [GDGVIT/gidget#33]
**This issue is extension of #23**

**Describe the bug**
To add your profile to widget, you have to search for your name, and add it to the widget.

**Expected behavior**
Add to widget button should be visible on profile section.

**Possible solution**
same as expected behavior.

#### Is this is a critical secuirty vulnerability?
- [ ] Yes: Please read code-of-conduct once
- [x] No

**Screenshots:**
![image](https://user-images.githubusercontent.com/52108077/124433026-e4958c80-dd8f-11eb-9cec-73a42d76bd1f.png)

![image](https://user-images.githubusercontent.com/52108077/124432971-d5164380-dd8f-11eb-8d8d-9cafa6fcc1e0.png)

**Comment by rishavnaskar** [comment]
@Nirmitjatana Implementing this is easy. We thought users might seldom want to add their own activity to the widget.
If anyone wants, they can simply search their username and add.
We can implement this if needed. @BRO3886

**Comment by BRO3886** [comment]
search and add works for now ig
