### ISSUE TITLE
Size of reload button is small

### ISSUE THREAD

**Issue by Nirmitjatana** [GDGVIT/gidget#34]
**Describe the bug**
This is a minor thing, but the reload button on widget is very small and I end missing it many times.

**Possible solution**
Increase the size of reload button on the widget a little

#### Is this is a critical secuirty vulnerability?
- [ ] Yes: Please read code-of-conduct once
- [x] No

**screenshot**
![image](https://user-images.githubusercontent.com/52108077/124435123-4951e680-dd92-11eb-90dd-b883248bcac5.png)

**Comment by rishavnaskar** [comment]
@Nirmitjatana Okay, will look into this.

**Comment by rishavnaskar** [comment]
@Nirmitjatana implemented.

**Comment by Nirmitjatana** [comment]
Great, closing this issue now!
